version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: pi-db
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3310:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pi-backend
    depends_on:
      - mysql
    ports:
      - "9090:9000"
    env_file:
      - .env
    environment:
      DB_PASS: ${DB_PASS}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      AUTH_ISSUER: ${AUTH_ISSUER}
      COOKIE_NAME: ${COOKIE_NAME}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PROTOCOL: ${DB_PROTOCOL}
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network: